# Generated by Django 4.2.5 on 2024-08-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_email_password_alter_emailletter_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailletter',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
