# Generated by Django 4.2.5 on 2024-08-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_emailletter_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailletter',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
