# Generated by Django 4.2.5 on 2024-08-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_emailletterfile_email_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailletterfile',
            name='name',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
