# Generated by Django 4.2.5 on 2024-08-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_emailletter_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailletter',
            name='sender',
            field=models.EmailField(max_length=254),
        ),
    ]
