# Generated by Django 4.2.5 on 2024-08-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_emailletterfile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailletter',
            name='date_received',
            field=models.DateField(blank=True, null=True),
        ),
    ]
