version: '3'

services:
  pgdb:
    image: postgres:latest
    container_name: pgdb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  back:
    env_file:
      - ".env"
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: back
    environment:
      DATABASE_NAME: mydatabase
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
      DATABASE_HOST: pgdb
      DATABASE_PORT: 5432
      env_email: ${env_email}
      env_password: ${env_password}
    command: >
      sh -c "python manage.py migrate &&
             echo \"from api.models import CustomUser; CustomUser.objects.create_superuser('$${env_email}', '$${env_email}', '$${env_password}') if not CustomUser.objects.filter(username='$${env_email}').exists() else None\" | python manage.py shell &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
    volumes:
      - media:/src/media/
      - static:/src/static/

  front:
    build:
      context: frontend
      dockerfile: ./Dockerfile
    container_name: front
    command: serve -s dist
    ports:
      - '3000:3000'

volumes:
  postgres_data:
  media:
  static:
